add a region-based constructor which uses the aws-region crate
meilisearch/strois pull request #1
Opened 2024-03-21 03:59 UTC by njaard

# Pull Request

## Related issue
Does not fix an issue

## What does this PR do?
- Makes it so you don't need to determine the URL if you only know the name of the AWS region

## PR checklist
Please check if your PR fulfills the following requirements:
- [ ] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [ ] Have you read the contributing guidelines?
- [×] Have you made sure that the title is accurate and descriptive of the changes?

2024-03-21 15:23 UTC, irevoire requested changes
Hey, thanks for your contribution, I think you forgot to update one last function

2024-03-21 15:23 UTC, irevoire commented on src/client.rs
> +    }
I guess we were supposed to take an AWS region in parameter here + it’s missing the doctest

2024-10-24 19:57 UTC, njaard commented
7 months later, but I fixed it!

I also improved the doctests for the other function

2024-11-05 10:25 UTC, irevoire approved these changes
Awesome! Thanks a lot @njaard 🫶 
Are you using strois in one of your project?

bors merge

2024-11-05 10:25 UTC, merged